version: "3"

env:
  LOCAL_PACKAGES:
    - ast

tasks:
  format:
    cmds:
      - go fmt ./...
    desc: Format the project
    dir: .

  switch-check:
    cmd: switch-check ./*/
    desc: Check the switch statements
    dir: .

  build:
    cmds:
      - go build -o build/regchecker .
    desc: Build the project
    deps:
      - format
      - switch-check
    dir: .

  clean:
    cmds:
      - rm build/regchecker
    deps:
      - enumer:clean
    desc: Clean the project
    dir: .
    ignore_error: true

  run:
    cmds:
      - ./build/regchecker
    desc: Run the project
    dir: .
    deps:
      - build

  test:
    cmds:
      - go test ./... -v
    desc: Run the tests
    dir: .
